// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/notes_api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Pass                 string   `protobuf:"bytes,3,opt,name=pass,proto3" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateRequest) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

type CreateResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateRequest struct {
	// id записи
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NameOld              string   `protobuf:"bytes,2,opt,name=name_old,json=nameOld,proto3" json:"name_old,omitempty"`
	NameNew              string   `protobuf:"bytes,3,opt,name=name_new,json=nameNew,proto3" json:"name_new,omitempty"`
	EmailNew             string   `protobuf:"bytes,4,opt,name=email_new,json=emailNew,proto3" json:"email_new,omitempty"`
	EmailOld             string   `protobuf:"bytes,5,opt,name=email_old,json=emailOld,proto3" json:"email_old,omitempty"`
	PassNew              string   `protobuf:"bytes,6,opt,name=pass_new,json=passNew,proto3" json:"pass_new,omitempty"`
	PassOld              string   `protobuf:"bytes,7,opt,name=pass_old,json=passOld,proto3" json:"pass_old,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{2}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateRequest) GetNameOld() string {
	if m != nil {
		return m.NameOld
	}
	return ""
}

func (m *UpdateRequest) GetNameNew() string {
	if m != nil {
		return m.NameNew
	}
	return ""
}

func (m *UpdateRequest) GetEmailNew() string {
	if m != nil {
		return m.EmailNew
	}
	return ""
}

func (m *UpdateRequest) GetEmailOld() string {
	if m != nil {
		return m.EmailOld
	}
	return ""
}

func (m *UpdateRequest) GetPassNew() string {
	if m != nil {
		return m.PassNew
	}
	return ""
}

func (m *UpdateRequest) GetPassOld() string {
	if m != nil {
		return m.PassOld
	}
	return ""
}

type UpdateResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{3}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ValidateRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Pass                 string   `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{4}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *ValidateRequest) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

type ValidateResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{5}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ValidateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*ValidateRequest)(nil), "ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "ValidateResponse")
}

func init() {
	proto.RegisterFile("api/notes_api.proto", fileDescriptor_4ff16eb62a4823ab)
}

var fileDescriptor_4ff16eb62a4823ab = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0x02, 0x31,
	0x10, 0x65, 0x91, 0x85, 0x65, 0x12, 0x3e, 0xac, 0x1c, 0x56, 0xbc, 0x98, 0x3d, 0x19, 0x4d, 0x4a,
	0xd4, 0x23, 0x37, 0x3c, 0x0b, 0x09, 0x89, 0x1e, 0xbc, 0x90, 0x9a, 0x9d, 0x90, 0xc6, 0x65, 0x5b,
	0xe9, 0x1a, 0xfe, 0x88, 0xff, 0xca, 0x3f, 0x65, 0xa6, 0xbb, 0x85, 0xed, 0xc6, 0xc4, 0x5b, 0x5f,
	0x5f, 0xe7, 0xf5, 0xbd, 0x99, 0x81, 0x0b, 0xa1, 0xe5, 0x2c, 0x57, 0x05, 0x9a, 0x8d, 0xd0, 0x92,
	0xeb, 0xbd, 0x2a, 0x54, 0xf2, 0x0c, 0x83, 0xa7, 0x3d, 0x8a, 0x02, 0xd7, 0xf8, 0xf9, 0x85, 0xa6,
	0x60, 0x0c, 0x3a, 0xb9, 0xd8, 0x61, 0x1c, 0x5c, 0x07, 0x37, 0xfd, 0xb5, 0x3d, 0xb3, 0x09, 0x84,
	0xb8, 0x13, 0x32, 0x8b, 0xdb, 0xf6, 0xb2, 0x04, 0xf4, 0x52, 0x0b, 0x63, 0xe2, 0xb3, 0xf2, 0x25,
	0x9d, 0x93, 0x5b, 0x18, 0x3a, 0x39, 0xa3, 0x55, 0x6e, 0x90, 0xc5, 0xd0, 0xdb, 0xa1, 0x31, 0x62,
	0xeb, 0x24, 0x1d, 0x4c, 0x7e, 0x02, 0x18, 0xbc, 0xe8, 0xb4, 0xf6, 0xf7, 0x04, 0xc2, 0x42, 0x7d,
	0x60, 0x5e, 0xbd, 0x2c, 0x01, 0xbb, 0x84, 0x88, 0x5c, 0x6c, 0x54, 0x96, 0x56, 0x06, 0x7a, 0x84,
	0x57, 0x59, 0x7a, 0xa4, 0x72, 0x3c, 0x54, 0x36, 0x2c, 0xb5, 0xc4, 0x03, 0xbb, 0x82, 0xbe, 0xb5,
	0x69, 0xb9, 0x8e, 0xe5, 0x22, 0x7b, 0xe1, 0x91, 0xa4, 0x19, 0xd6, 0xc8, 0x4a, 0x94, 0xb2, 0xd8,
	0xc2, 0x6e, 0x29, 0x4a, 0x98, 0xea, 0x1c, 0x45, 0x65, 0xbd, 0x13, 0xb5, 0xca, 0x52, 0x4a, 0xee,
	0xc2, 0xfc, 0x9b, 0x7c, 0x0e, 0xa3, 0x57, 0x91, 0xc9, 0x46, 0xf4, 0x4c, 0x6d, 0xe5, 0x31, 0xba,
	0x05, 0xc7, 0x16, 0xb7, 0x6b, 0x2d, 0x5e, 0xc0, 0xf8, 0x54, 0x5c, 0x7d, 0xf5, 0x77, 0xe3, 0x6a,
	0x06, 0xda, 0x9e, 0x81, 0x87, 0xef, 0x00, 0xc2, 0x25, 0x6d, 0x02, 0xbb, 0x83, 0x6e, 0x39, 0x30,
	0x36, 0xe4, 0xde, 0x22, 0x4c, 0x47, 0xdc, 0x9f, 0x64, 0xd2, 0x62, 0xf7, 0x10, 0xb9, 0xaf, 0xd9,
	0x98, 0x37, 0x22, 0x4c, 0xcf, 0x79, 0xd3, 0x57, 0xd2, 0x22, 0xfd, 0xb2, 0x2d, 0x6c, 0xc8, 0xbd,
	0x61, 0x4f, 0x47, 0xdc, 0xef, 0x57, 0xd2, 0x5a, 0xc0, 0x5b, 0x34, 0x13, 0x5a, 0xce, 0x85, 0x96,
	0xef, 0x5d, 0xbb, 0x9f, 0x8f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x60, 0xeb, 0xd5, 0x95, 0xb6,
	0x02, 0x00, 0x00,
}
