// Code generated by mfd-generator v0.4.4; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

var Columns = struct {
	Users struct {
		ID, Name, Email, Pass string
	}
}{
	Users: struct {
		ID, Name, Email, Pass string
	}{
		ID:    "id",
		Name:  "name",
		Email: "email",
		Pass:  "pass",
	},
}

var Tables = struct {
	Users struct {
		Name, Alias string
	}
}{
	Users: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
}

type Users struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID    int64  `pg:"id,pk"`
	Name  string `pg:"name,pk"`
	Email string `pg:"email,pk"`
	Pass  string `pg:"pass,pk"`
}
